server:  
  servlet-path: /demo
  port: 8080
spring: 
    jersey: 
        application-path: /demo/rest
    datasource:  
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&charaterEncoding=utf-8&useSSL=false
        username: root
        password: root
    thymeleaf:
       cache: false
       mode: LEGACYHTML5
        